'use client';
import {useMemo,useState} from 'react';
const safe=v=>Math.max(0,Number(v)||0);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
export default function CarAffordabilityCalculator(){
 const [salary,setSalary]=useState(75000),[takeHome,setTakeHome]=useState(0),[debt,setDebt]=useState(500),[down,setDown]=useState(5000),[trade,setTrade]=useState(0),[apr,setApr]=useState(7),[term,setTerm]=useState(60),[tax,setTax]=useState(7),[fees,setFees]=useState(800),[insurance,setInsurance]=useState(180),[fuel,setFuel]=useState(180),[maintenance,setMaintenance]=useState(75);
 const r=useMemo(()=>{const gross=safe(salary)/12;const net=safe(takeHome)>0?safe(takeHome):gross*.76;const operating=safe(insurance)+safe(fuel)+safe(maintenance);const conservative=Math.max(0,net*.15-operating-safe(debt)*.1);const payment=Math.min(conservative,Math.max(0,gross*.10));const n=Math.max(1,safe(term));const mr=safe(apr)/1200;const financed=mr>0?payment*(1-Math.pow(1+mr,-n))/mr:payment*n;const buyingPower=Math.max(0,(financed+safe(down)+safe(trade)-safe(fees))/(1+safe(tax)/100));const totalCar=payment+operating;return {gross,net,operating,payment,financed,buyingPower,totalCar,share:net?totalCar/net*100:0}},[salary,takeHome,debt,down,trade,apr,term,tax,fees,insurance,fuel,maintenance]);
 return <section className="mortgageCalc"><div className="mortgageInputs"><div className="eyebrow">CAR AFFORDABILITY</div><h2>Estimate a practical vehicle budget</h2><p>Enter your income, debts, loan terms and ownership costs. Results update instantly.</p><div className="mortgageGrid"><Field label="Annual gross salary" value={salary} set={setSalary}/><Field label="Monthly take-home (optional)" value={takeHome} set={setTakeHome}/><Field label="Other monthly debt" value={debt} set={setDebt}/><Field label="Down payment" value={down} set={setDown}/><Field label="Trade-in value" value={trade} set={setTrade}/><Field label="APR (%)" value={apr} set={setApr} step="0.1"/><div><label>Loan term</label><select value={term} onChange={e=>setTerm(+e.target.value)}>{[36,48,60,72,84].map(x=><option key={x} value={x}>{x} months</option>)}</select></div><Field label="Sales tax (%)" value={tax} set={setTax} step="0.1"/><Field label="Dealer/title fees" value={fees} set={setFees}/><Field label="Insurance / month" value={insurance} set={setInsurance}/><Field label="Fuel / month" value={fuel} set={setFuel}/><Field label="Maintenance / month" value={maintenance} set={setMaintenance}/></div><small>If take-home is blank, AffordBase uses a simple 76% planning estimate. Taxes, registration and financing rules vary by location and borrower.</small></div><div className="mortgageResults"><div className="eyebrow">ESTIMATED BUDGET</div><div className="homePrice"><span>Estimated vehicle price</span><strong>{money(r.buyingPower)}</strong><small>before any location-specific incentives or adjustments</small></div><div className="mortgageCards"><Metric t="Target loan payment" v={`${money(r.payment)}/mo`}/><Metric t="Estimated amount financed" v={money(r.financed)}/><Metric t="Ownership costs" v={`${money(r.operating)}/mo`}/><Metric t="Car cost / take-home" v={`${r.share.toFixed(1)}%`} bad={r.share>20}/></div><div className="mortgagePlan"><h3>Monthly car budget</h3><Row t="Estimated take-home" v={money(r.net)}/><Row t="Loan payment" v={money(r.payment)}/><Row t="Insurance" v={money(insurance)}/><Row t="Fuel" v={money(fuel)}/><Row t="Maintenance reserve" v={money(maintenance)}/><Row t="Total monthly car cost" v={money(r.totalCar)}/></div><div className="mortgageNote"><b>Planning rule:</b> AffordBase caps the modeled loan payment at about 10% of gross monthly income and also checks total car costs against take-home pay. This is a budgeting guideline, not lender approval.</div></div></section>
}
function Field({label,value,set,step='1'}){return <div><label>{label}</label><input type="number" min="0" step={step} value={value} onChange={e=>set(safe(e.target.value))}/></div>}
function Metric({t,v,bad}){return <div className={bad?'mortgageMetric bad':'mortgageMetric'}><span>{t}</span><strong>{v}</strong></div>}
function Row({t,v}){return <div><span>{t}</span><b>{v}</b></div>}
