'use client';
import {useMemo,useState} from 'react';
const safe=v=>Math.max(0,Number(v)||0);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
export default function CarAffordabilityBySalary(){
 const [salary,setSalary]=useState(75000),[takeHomeRate,setTakeHomeRate]=useState(76),[debt,setDebt]=useState(500),[down,setDown]=useState(5000),[trade,setTrade]=useState(0),[apr,setApr]=useState(7),[term,setTerm]=useState(60),[tax,setTax]=useState(7),[fees,setFees]=useState(800),[insurance,setInsurance]=useState(180),[fuel,setFuel]=useState(180),[maintenance,setMaintenance]=useState(75);
 const r=useMemo(()=>{const annual=safe(salary),gross=annual/12,net=gross*Math.min(100,safe(takeHomeRate))/100,operating=safe(insurance)+safe(fuel)+safe(maintenance);const grossCap=gross*.10;const netCap=Math.max(0,net*.15-operating-safe(debt)*.10);const payment=Math.max(0,Math.min(grossCap,netCap));const n=Math.max(1,safe(term));const mr=safe(apr)/1200;const financed=mr>0?payment*(1-Math.pow(1+mr,-n))/mr:payment*n;const price=Math.max(0,(financed+safe(down)+safe(trade)-safe(fees))/(1+safe(tax)/100));const allIn=payment+operating;return {gross,net,operating,payment,financed,price,allIn,share:net?allIn/net*100:0}},[salary,takeHomeRate,debt,down,trade,apr,term,tax,fees,insurance,fuel,maintenance]);
 return <section className="mortgageCalc"><div className="mortgageInputs"><div className="eyebrow">CAR BUDGET BY SALARY</div><h2>Turn your salary into a car-price estimate</h2><p>Adjust salary, financing and ownership costs to see a practical vehicle-price range.</p><div className="mortgageGrid"><Field label="Annual gross salary" value={salary} set={setSalary}/><Field label="Estimated take-home (%)" value={takeHomeRate} set={setTakeHomeRate} step="0.5"/><Field label="Other monthly debt" value={debt} set={setDebt}/><Field label="Down payment" value={down} set={setDown}/><Field label="Trade-in value" value={trade} set={setTrade}/><Field label="APR (%)" value={apr} set={setApr} step="0.1"/><div><label>Loan term</label><select value={term} onChange={e=>setTerm(+e.target.value)}>{[36,48,60,72,84].map(x=><option key={x} value={x}>{x} months</option>)}</select></div><Field label="Sales tax (%)" value={tax} set={setTax} step="0.1"/><Field label="Dealer/title fees" value={fees} set={setFees}/><Field label="Insurance / month" value={insurance} set={setInsurance}/><Field label="Fuel / charging / month" value={fuel} set={setFuel}/><Field label="Maintenance / month" value={maintenance} set={setMaintenance}/></div><small>The take-home percentage is an editable planning assumption, not a tax calculation. Use AffordBase's take-home pay tools for a location-specific estimate.</small></div><div className="mortgageResults"><div className="eyebrow">SALARY-BASED ESTIMATE</div><div className="homePrice"><span>Estimated affordable vehicle price</span><strong>{money(r.price)}</strong><small>based on the assumptions you entered</small></div><div className="mortgageCards"><Metric t="Target loan payment" v={`${money(r.payment)}/mo`}/><Metric t="Amount financed" v={money(r.financed)}/><Metric t="Operating costs" v={`${money(r.operating)}/mo`}/><Metric t="All-in / take-home" v={`${r.share.toFixed(1)}%`} bad={r.share>20}/></div><div className="mortgagePlan"><h3>How your salary maps to the budget</h3><Row t="Gross monthly income" v={money(r.gross)}/><Row t="Estimated take-home" v={money(r.net)}/><Row t="Target loan payment" v={money(r.payment)}/><Row t="Insurance + fuel + maintenance" v={money(r.operating)}/><Row t="Estimated all-in car cost" v={money(r.allIn)}/></div><div className="mortgageNote"><b>Planning approach:</b> the modeled loan payment is capped at about 10% of gross monthly income and checked against take-home income after recurring ownership costs and a small allowance for other debt. Change the inputs to match your own budget.</div></div></section>
}
function Field({label,value,set,step='1'}){return <div><label>{label}</label><input type="number" min="0" step={step} value={value} onChange={e=>set(safe(e.target.value))}/></div>}
function Metric({t,v,bad}){return <div className={bad?'mortgageMetric bad':'mortgageMetric'}><span>{t}</span><strong>{v}</strong></div>}
function Row({t,v}){return <div><span>{t}</span><b>{v}</b></div>}
