'use client';
import {useMemo,useState} from 'react';
const safe=v=>Math.max(0,Number(v)||0);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
export default function CarTotalCostCalculator(){
 const [price,setPrice]=useState(35000),[down,setDown]=useState(5000),[trade,setTrade]=useState(0),[apr,setApr]=useState(7),[term,setTerm]=useState(60),[tax,setTax]=useState(7),[fees,setFees]=useState(800),[insurance,setInsurance]=useState(180),[fuel,setFuel]=useState(180),[maintenance,setMaintenance]=useState(75),[registration,setRegistration]=useState(15),[parking,setParking]=useState(0),[years,setYears]=useState(5),[resalePct,setResalePct]=useState(50);
 const r=useMemo(()=>{const p=safe(price),dp=safe(down),tr=safe(trade),taxAmt=p*safe(tax)/100,principal=Math.max(0,p+taxAmt+safe(fees)-dp-tr),n=Math.max(1,safe(term)),mr=safe(apr)/1200,payment=principal===0?0:(mr>0?principal*mr/(1-Math.pow(1+mr,-n)):principal/n),loanPaid=payment*n,interest=Math.max(0,loanPaid-principal),monthlyOps=safe(insurance)+safe(fuel)+safe(maintenance)+safe(registration)+safe(parking),horizon=Math.max(1,safe(years))*12,operating=monthlyOps*horizon,resale=p*safe(resalePct)/100,totalCash=dp+tr+loanPaid+operating,resaleAdjusted=Math.max(0,totalCash-resale),monthlyTrue=resaleAdjusted/horizon;return {taxAmt,principal,payment,interest,monthlyOps,operating,resale,totalCash,resaleAdjusted,monthlyTrue,horizon}},[price,down,trade,apr,term,tax,fees,insurance,fuel,maintenance,registration,parking,years,resalePct]);
 return <section className="mortgageCalc"><div className="mortgageInputs"><div className="eyebrow">TOTAL CAR COST</div><h2>Estimate the real cost of owning a car</h2><p>Combine financing, taxes and fees with recurring ownership costs and an estimated resale value.</p><div className="mortgageGrid"><Field label="Vehicle price" value={price} set={setPrice}/><Field label="Down payment" value={down} set={setDown}/><Field label="Trade-in value" value={trade} set={setTrade}/><Field label="APR (%)" value={apr} set={setApr} step="0.1"/><div><label>Loan term</label><select value={term} onChange={e=>setTerm(+e.target.value)}>{[36,48,60,72,84].map(x=><option key={x} value={x}>{x} months</option>)}</select></div><Field label="Sales tax (%)" value={tax} set={setTax} step="0.1"/><Field label="Dealer/title fees" value={fees} set={setFees}/><Field label="Insurance / month" value={insurance} set={setInsurance}/><Field label="Fuel or charging / month" value={fuel} set={setFuel}/><Field label="Maintenance / month" value={maintenance} set={setMaintenance}/><Field label="Registration / month" value={registration} set={setRegistration}/><Field label="Parking / month" value={parking} set={setParking}/><Field label="Ownership period (years)" value={years} set={setYears} step="1"/><Field label="Estimated resale value (%)" value={resalePct} set={setResalePct} step="1"/></div><small>Use your local tax, fees and real insurance quote when available. Resale value is an editable planning assumption, not a forecast.</small></div><div className="mortgageResults"><div className="eyebrow">TRUE-COST ESTIMATE</div><div className="homePrice"><span>Resale-adjusted cost</span><strong>{money(r.resaleAdjusted)}</strong><small>over {years || 0} years · about {money(r.monthlyTrue)}/month</small></div><div className="mortgageCards"><Metric t="Loan payment" v={`${money(r.payment)}/mo`}/><Metric t="Total interest" v={money(r.interest)}/><Metric t="Operating costs" v={`${money(r.monthlyOps)}/mo`}/><Metric t="Estimated resale value" v={money(r.resale)}/></div><div className="mortgagePlan"><h3>Cost breakdown</h3><Row t="Vehicle price" v={money(price)}/><Row t="Sales tax" v={money(r.taxAmt)}/><Row t="Amount financed" v={money(r.principal)}/><Row t="Interest over loan" v={money(r.interest)}/><Row t={`Operating costs (${years || 0} years)`} v={money(r.operating)}/><Row t="Cash outflow before resale" v={money(r.totalCash)}/><Row t="Less estimated resale" v={`− ${money(r.resale)}`}/><Row t="Estimated net ownership cost" v={money(r.resaleAdjusted)}/></div><div className="mortgageNote"><b>Planning note:</b> depreciation is represented through the resale-value assumption. Actual repair costs, insurance, fuel prices, taxes and resale value can differ substantially.</div></div></section>
}
function Field({label,value,set,step='1'}){return <div><label>{label}</label><input type="number" min="0" step={step} value={value} onChange={e=>set(safe(e.target.value))}/></div>}
function Metric({t,v}){return <div className="mortgageMetric"><span>{t}</span><strong>{v}</strong></div>}
function Row({t,v}){return <div><span>{t}</span><b>{v}</b></div>}
