'use client';
import {useMemo,useState} from 'react';
const safe=v=>Math.max(0,Number(v)||0);
const money=(n,c)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
export default function ClosingCostCalculator(){
 const [country,setCountry]=useState('CA'),[price,setPrice]=useState(600000),[pct,setPct]=useState(2.5),[legal,setLegal]=useState(1500),[inspection,setInspection]=useState(500),[other,setOther]=useState(1000),[credits,setCredits]=useState(0),[downPct,setDownPct]=useState(20);
 const r=useMemo(()=>{const currency=country==='CA'?'CAD':'USD',base=price*safe(pct)/100,extras=safe(legal)+safe(inspection)+safe(other),closing=Math.max(0,base+extras-safe(credits)),down=price*safe(downPct)/100,cash=down+closing;return {currency,base,extras,closing,down,cash}},[country,price,pct,legal,inspection,other,credits,downPct]);
 return <section className="cashCalc"><div className="cashInputs"><div className="eyebrow">CLOSING COST PLANNER</div><h2>Estimate costs due around closing</h2><p>Start with a percentage estimate, then add transaction-specific items and subtract any credits you expect.</p>
 <label>Country</label><select value={country} onChange={e=>{const c=e.target.value;setCountry(c);setPct(c==='CA'?2.5:3);}}><option value="CA">🇨🇦 Canada</option><option value="US">🇺🇸 United States</option></select>
 <div className="cashGrid"><Field label="Home purchase price" value={price} set={setPrice} step="5000"/><Field label="Base closing-cost estimate (%)" value={pct} set={setPct} step="0.1"/><Field label="Legal / title / settlement estimate" value={legal} set={setLegal} step="100"/><Field label="Inspection / appraisal estimate" value={inspection} set={setInspection} step="100"/><Field label="Other taxes, fees & adjustments" value={other} set={setOther} step="100"/><Field label="Seller / lender credits" value={credits} set={setCredits} step="100"/><Field label="Down payment (%)" value={downPct} set={setDownPct} step="0.5"/></div>
 <small>{country==='CA'?'CMHC describes closing costs as commonly about 1.5%–4% of the purchase price.':'CFPB says U.S. closing costs are typically about 2%–5% of the purchase price, excluding the down payment.'} The percentage is only a planning range; actual charges depend on the property, loan and location.</small></div>
 <div className="cashResults"><div className="eyebrow">ESTIMATED CLOSING COSTS</div><div className="cashHero"><span>Estimated closing costs</span><strong>{money(r.closing,r.currency)}</strong><small>before your down payment</small></div><div className="cashCards"><Metric t="Base percentage estimate" v={money(r.base,r.currency)} s={`${safe(pct).toFixed(1)}% of purchase price`}/><Metric t="Added item estimates" v={money(r.extras,r.currency)} s="legal/title + inspection/appraisal + other"/><Metric t="Estimated down payment" v={money(r.down,r.currency)} s={`${safe(downPct).toFixed(1)}% of purchase price`}/><Metric t="Estimated cash to plan for" v={money(r.cash,r.currency)} s="down payment + estimated closing costs"/></div><div className="savingsTimeline"><h3>What can be included?</h3><Row t="Legal, title or settlement services" v="Varies"/><Row t="Transfer / recording taxes and fees" v="Location-specific"/><Row t="Inspection and appraisal" v="Transaction-specific"/><Row t="Prepaids and adjustments" v="May apply"/></div></div></section>
}
function Field({label,value,set,step='1'}){return <div><label>{label}</label><input type="number" min="0" step={step} value={value} onChange={e=>set(safe(e.target.value))}/></div>}
function Metric({t,v,s}){return <div className="cashMetric"><span>{t}</span><strong>{v}</strong><small>{s}</small></div>}
function Row({t,v}){return <div><span>{t}</span><b>{v}</b></div>}
