'use client';
import {useMemo,useState} from 'react';
import {CITY_DATA} from '../cityData';
const safe=v=>Math.max(0,Number(v)||0);
const money=(n,c)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
export default function DownPaymentClosingCosts({initialHomePrice=500000,initialCity='Toronto'}){
 const [city,setCity]=useState(CITY_DATA[initialCity]?initialCity:'Toronto'),[price,setPrice]=useState(safe(initialHomePrice)||500000),[downMode,setDownMode]=useState('percent'),[down,setDown]=useState(15),[closingPct,setClosingPct]=useState(2.5),[other,setOther]=useState(3000),[saved,setSaved]=useState(35000),[monthlySave,setMonthlySave]=useState(1200);
 const r=useMemo(()=>{const d=CITY_DATA[city],currency=d.currency,downAmount=downMode==='percent'?price*safe(down)/100:safe(down),downPct=price>0?downAmount/price*100:0,closing=price*safe(closingPct)/100,cash=downAmount+closing+safe(other),mortgage=Math.max(0,price-downAmount),gap=Math.max(0,cash-safe(saved)),months=gap<=0?0:(safe(monthlySave)>0?Math.ceil(gap/safe(monthlySave)):null);return {d,currency,downAmount,downPct,closing,cash,mortgage,gap,months}},[city,price,downMode,down,closingPct,other,saved,monthlySave]);
 const timeline=r.months===null?'Add monthly savings':r.months===0?'Ready now':`${r.months} months (~${(r.months/12).toFixed(1)} years)`;
 return <section className="cashCalc"><div className="cashInputs"><div className="eyebrow">UPFRONT CASH PLANNER</div><h2>How much cash do you need to buy?</h2><p>Combine your down payment, estimated closing costs and other upfront costs, then compare the target with your savings.</p>
 <label>City</label><select value={city} onChange={e=>setCity(e.target.value)}>{Object.entries(CITY_DATA).map(([n,d])=><option key={n} value={n}>{d.country==='CA'?'🇨🇦':'🇺🇸'} {n}</option>)}</select>
 <div className="cashGrid"><Field label="Home price" value={price} set={setPrice}/><div><label>Down payment type</label><select value={downMode} onChange={e=>{setDownMode(e.target.value);setDown(e.target.value==='percent'?15:75000)}}><option value="percent">Percent (%)</option><option value="amount">Cash amount</option></select></div><Field label={downMode==='percent'?'Down payment (%)':'Down payment amount'} value={down} set={setDown} step={downMode==='percent'?'0.5':'1000'}/><Field label="Closing costs estimate (%)" value={closingPct} set={setClosingPct} step="0.1"/><Field label="Other upfront costs" value={other} set={setOther}/><Field label="Savings already available" value={saved} set={setSaved}/><Field label="Monthly savings" value={monthlySave} set={setMonthlySave}/></div>
 <small>Closing costs are an adjustable planning estimate, not a fixed legal rate. Actual land-transfer/recording fees, legal/title costs, inspections, lender fees, taxes and insurance vary by location and transaction.</small></div>
 <div className="cashResults"><div className="eyebrow">CASH TARGET</div><div className="cashHero"><span>Estimated cash needed to buy</span><strong>{money(r.cash,r.currency)}</strong><small>down payment + estimated closing costs + other upfront costs</small></div><div className="cashCards"><Metric t="Down payment" v={money(r.downAmount,r.currency)} s={`${r.downPct.toFixed(1)}% of price`}/><Metric t="Closing costs" v={money(r.closing,r.currency)} s={`${safe(closingPct).toFixed(1)}% assumption`}/><Metric t="Mortgage amount" v={money(r.mortgage,r.currency)} s="before lender-specific adjustments"/><Metric t="Cash still needed" v={money(r.gap,r.currency)} s={r.gap===0?'target covered by entered savings':'after current savings'}/></div>
 <div className="savingsTimeline"><h3>Savings timeline</h3><div className="timelineBig"><span>Estimated time to cash target</span><strong>{timeline}</strong></div><Row t="Current savings" v={money(saved,r.currency)}/><Row t="Monthly savings" v={`${money(monthlySave,r.currency)}/mo`}/><Row t="Remaining gap" v={money(r.gap,r.currency)}/>{r.months!==null&&r.months>0?<Row t="Projected additional savings" v={money(r.months*safe(monthlySave),r.currency)}/>:null}</div></div></section>
}
function Field({label,value,set,step='1'}){return <div><label>{label}</label><input type="number" min="0" step={step} value={value} onChange={e=>set(safe(e.target.value))}/></div>}
function Metric({t,v,s}){return <div className="cashMetric"><span>{t}</span><strong>{v}</strong><small>{s}</small></div>}
function Row({t,v}){return <div><span>{t}</span><b>{v}</b></div>}
