'use client';
import {useMemo,useState} from 'react';

const safe=v=>Math.max(0,Number(v)||0);
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
function payment(principal,annualRate,years){const n=Math.max(1,years*12),r=safe(annualRate)/1200;if(!r)return principal/n;return principal*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1)}

export default function MortgageStressTestCanada(){
 const [mortgage,setMortgage]=useState(500000),[rate,setRate]=useState(4.75),[years,setYears]=useState(25),[income,setIncome]=useState(120000),[tax,setTax]=useState(450),[heat,setHeat]=useState(150),[condo,setCondo]=useState(0),[debt,setDebt]=useState(500);
 const r=useMemo(()=>{const qualifying=Math.max(5.25,safe(rate)+2),p=payment(safe(mortgage),qualifying,years),gross=safe(income)/12,housing=p+safe(tax)+safe(heat)+safe(condo)*.5,gds=gross?housing/gross*100:0,tds=gross?(housing+safe(debt))/gross*100:0;return{qualifying,p,gds,tds,passG:gds<=39,passT:tds<=44}},[mortgage,rate,years,income,tax,heat,condo,debt]);
 return <section className="mortgageCalc"><div className="mortgageInputs"><div className="eyebrow">CANADA STRESS TEST</div><h2>Estimate mortgage stress-test qualification</h2><p>Compare your contract rate with the qualifying rate and estimate GDS and TDS using your housing costs and debt.</p><div className="mortgageGrid"><Field label="Mortgage amount" value={mortgage} set={setMortgage}/><Field label="Contract rate (%)" value={rate} set={setRate} step="0.01"/><div><label>Amortization</label><select value={years} onChange={e=>setYears(+e.target.value)}>{[15,20,25,30].map(x=><option key={x}>{x}</option>)}</select></div><Field label="Gross household income / year" value={income} set={setIncome}/><Field label="Property tax / month" value={tax} set={setTax}/><Field label="Heating / month" value={heat} set={setHeat}/><Field label="Condo fees / month" value={condo} set={setCondo}/><Field label="Other debt / month" value={debt} set={setDebt}/></div><small>Educational estimate only. Lenders may calculate qualifying payments, income and debt differently and may apply additional underwriting requirements.</small></div><div className="mortgageResults"><div className="eyebrow">QUALIFYING ESTIMATE</div><div className="homePrice"><span>Stress-test qualifying rate</span><strong>{r.qualifying.toFixed(2)}%</strong><small>higher of 5.25% or contract rate + 2%</small></div><div className="mortgageCards"><Metric t="Payment at qualifying rate" v={money(r.p)+'/mo'}/><Metric t="GDS estimate" v={r.gds.toFixed(1)+'%'} bad={!r.passG}/><Metric t="TDS estimate" v={r.tds.toFixed(1)+'%'} bad={!r.passT}/><Metric t="Reference check" v={r.passG&&r.passT?'Within 39% / 44%':'Above reference'} bad={!(r.passG&&r.passT)}/></div></div></section>
}
function Field({label,value,set,step='1'}){return <div><label>{label}</label><input type="number" min="0" step={step} value={value} onChange={e=>set(safe(e.target.value))}/></div>}
function Metric({t,v,bad}){return <div className={bad?'mortgageMetric bad':'mortgageMetric'}><span>{t}</span><strong>{v}</strong></div>}