'use client';
import {useMemo,useState} from 'react';
import {canadaTax,usaTax} from '../tax';
import {CITY_DATA} from '../cityData';
const safe=v=>Math.max(0,Number(v)||0);
const money=(n,c)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
const monthlyPayment=(principal,annualRate,years)=>{const n=Math.max(1,years*12),r=Math.max(0,annualRate)/1200;if(!r)return principal/n;return principal*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1)};
export default function MortgageAffordability(){
 const [city,setCity]=useState('Toronto'),[salary,setSalary]=useState(100000),[down,setDown]=useState(80000),[rate,setRate]=useState(5),[term,setTerm]=useState(25),[debt,setDebt]=useState(500),[propertyTax,setPropertyTax]=useState(450),[insurance,setInsurance]=useState(140),[fees,setFees]=useState(0);
 const r=useMemo(()=>{const d=CITY_DATA[city],tax=d.country==='CA'?canadaTax(salary,d.region):usaTax(salary,d.region,'single'),net=tax.net/12,gross=salary/12,other=safe(propertyTax)+safe(insurance)+safe(fees),paymentCap=Math.max(0,Math.min(net*.35-other-debt*.15,gross*.39-other-safe(debt))),n=Math.max(1,safe(term)*12),mr=safe(rate)/1200;let mortgage=paymentCap*n;if(mr>0) mortgage=paymentCap*(Math.pow(1+mr,n)-1)/(mr*Math.pow(1+mr,n));const home=mortgage+safe(down),payment=monthlyPayment(mortgage,safe(rate),safe(term)),housing=payment+other,dti=gross>0?(housing+safe(debt))/gross*100:0,left=net-housing-safe(debt);return {d,tax,net,gross,mortgage,home,payment,housing,dti,left,other}},[city,salary,down,rate,term,debt,propertyTax,insurance,fees]);
 const c=r.d.currency;
 return <section className="mortgageCalc"><div className="mortgageInputs"><div className="eyebrow">HOME AFFORDABILITY</div><h2>Estimate your home-buying range</h2><p>Adjust income, down payment, rate and monthly obligations. Results update instantly.</p>
 <label>City</label><select value={city} onChange={e=>setCity(e.target.value)}>{Object.entries(CITY_DATA).map(([n,d])=><option key={n} value={n}>{d.country==='CA'?'🇨🇦':'🇺🇸'} {n}</option>)}</select>
 <div className="mortgageGrid"><Field label="Annual gross salary" value={salary} set={setSalary}/><Field label="Down payment" value={down} set={setDown}/><Field label="Interest rate (%)" value={rate} set={setRate} step="0.1"/><div><label>Mortgage term</label><select value={term} onChange={e=>setTerm(+e.target.value)}>{[15,20,25,30].map(x=><option key={x} value={x}>{x} years</option>)}</select></div><Field label="Monthly debt" value={debt} set={setDebt}/><Field label="Property tax / month" value={propertyTax} set={setPropertyTax}/><Field label="Home insurance / month" value={insurance} set={setInsurance}/><Field label="HOA / condo fees / month" value={fees} set={setFees}/></div>
 <small>Planning estimate only. Qualification rules, stress tests, mortgage insurance, closing costs, local taxes and lender underwriting are not fully modeled.</small></div>
 <div className="mortgageResults"><div className="eyebrow">ESTIMATED RANGE</div><div className="homePrice"><span>Estimated affordable home price</span><strong>{money(r.home,c)}</strong><small>including your entered down payment</small></div><div className="mortgageCards"><Metric t="Maximum mortgage" v={money(r.mortgage,c)}/><Metric t="Mortgage payment" v={`${money(r.payment,c)}/mo`}/><Metric t="Total housing cost" v={`${money(r.housing,c)}/mo`}/><Metric t="Money left" v={`${money(r.left,c)}/mo`} bad={r.left<0}/></div>
 <div className="mortgagePlan"><h3>Monthly affordability breakdown</h3><Row t="Estimated take-home" v={money(r.net,c)}/><Row t="Mortgage principal + interest" v={money(r.payment,c)}/><Row t="Property tax" v={money(propertyTax,c)}/><Row t="Insurance" v={money(insurance,c)}/><Row t="HOA / condo fees" v={money(fees,c)}/><Row t="Other debt" v={money(debt,c)}/><Row t="Debt-to-income estimate" v={`${r.dti.toFixed(1)}%`}/></div>
 <a className="cashNeededBtn" href={`/down-payment-calculator/?home=${Math.round(r.home)}&city=${encodeURIComponent(city)}`}>Calculate cash needed for this home →</a><div className="mortgageNote"><b>Important:</b> This is a budgeting range, not a mortgage pre-approval. Canada and U.S. lending rules differ and lenders may qualify you for a different amount.</div></div></section>}
function Field({label,value,set,step='1'}){return <div><label>{label}</label><input type="number" min="0" step={step} value={value} onChange={e=>set(safe(e.target.value))}/></div>}
function Metric({t,v,bad}){return <div className={bad?'mortgageMetric bad':'mortgageMetric'}><span>{t}</span><strong>{v}</strong></div>}
function Row({t,v}){return <div><span>{t}</span><b>{v}</b></div>}
