'use client';
import {useMemo,useState} from 'react';import {canadaTax,usaTax} from './tax';import {CA_PROVINCES,US_STATES} from './taxData';
const money=(n,c)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:0}).format(n||0);
export default function Home(){
 const [country,setCountry]=useState('CA'),[region,setRegion]=useState('ON'),[salary,setSalary]=useState(75000),[debt,setDebt]=useState(400),[rent,setRent]=useState(1800),[car,setCar]=useState(450);const currency=country==='CA'?'CAD':'USD';
 const r=useMemo(()=>{const t=country==='CA'?canadaTax(salary,region):usaTax(salary,region,'single');const net=t.net/12;const comfortable=Math.max(0,net*.30-debt*.15),max=Math.max(0,net*.36-debt*.25),carBudget=Math.max(0,net*.10),living=net*.30,save=net*.15,left=net-rent-car-living-save-debt;return {net,comfortable,max,carBudget,living,save,left,t}},[salary,debt,rent,car,country,region]);
 function swap(c){setCountry(c);setRegion(c==='CA'?'ON':'TX')}
 return <><header><a className="brand" href="#">AffordBase<span>.</span></a><nav><a href="/dashboard/">Dashboard</a><a href="#rent">Rent</a><a href="/take-home-pay-calculator/">Salary</a><a href="/car-affordability-calculator/">Car</a><a href="/compare-cities/">Compare Cities</a><a href="/salary-needed-calculator/">Salary Needed</a><a href="/mortgage-affordability-calculator/">Home</a><a href="/down-payment-calculator/">Cash Needed</a><a href="/my-plan/">My Plan</a><a href="/goal-planner/">Goal Planner</a></nav><a className="mini" href="#calculator">Calculate my budget</a></header><main><section className="home-hero">
  <div className="home-hero-copy"><div className="pill">🇨🇦 CANADA & 🇺🇸 U.S. · 2026 DATA · FREE CALCULATORS</div><h1>A Brighter Financial<br/>Future Is <em>Within Reach.</em></h1><p>Compare costs, calculate your take-home pay, plan for a home, and see how far your money can go in Canada and the U.S.</p></div>
  <div className="hero-mini-grid"><a className="hero-mini salary-mini" href="/take-home-pay-calculator/"><i>💰</i><div><b>Salary Calculator</b><span>Find your take-home pay in seconds.</span></div><strong>→</strong></a><a className="hero-mini rent-mini" href="/rent-affordability-calculator/"><i>🏠</i><div><b>Rent Affordability</b><span>See what you can afford in any city.</span></div><strong>→</strong></a><a className="hero-mini home-mini" href="/mortgage-affordability-calculator/"><i>🏡</i><div><b>Home Affordability</b><span>Check your buying power and payment.</span></div><strong>→</strong></a></div>
  <div className="hero-city-search"><span>🌆 Compare Toronto, Vancouver, Montreal, New York, Miami…</span><a href="/compare-cities/">Compare Cities →</a></div>
  <div className="hero-city-pills"><b>Popular:</b><a href="/cities/toronto/">Toronto</a><a href="/cities/vancouver/">Vancouver</a><a href="/cities/montreal/">Montreal</a><a href="/cities/calgary/">Calgary</a><a href="/cities/new-york/">New York</a><a href="/cities/miami/">Miami</a><a href="/cities/los-angeles/">Los Angeles</a><a href="/cities/chicago/">Chicago</a></div>
 </section>
 <section className="home-trust"><div><b>✓ Free calculators</b><span>Always free to use</span></div><div><b>🌎 Canada & U.S. cities</b><span>Updated for 2026</span></div><div><b>⚡ No signup required</b><span>Start planning instantly</span></div><div><b>📊 Connected planning</b><span>Salary · rent · car · home</span></div></section>
 <section className="life-strip home-popular" aria-label="Popular calculators"><div className="popular-title"><span>EXPLORE OUR TOOLS</span><h2>Popular Calculators</h2></div><a className="life-card life-save" href="/take-home-pay-calculator/"><div><b>Salary Calculator</b><span>Calculate take-home pay</span></div></a><a className="life-card life-rent" href="/rent-affordability-calculator/"><div><b>Rent Affordability</b><span>Find a comfortable monthly rent</span></div></a><a className="life-card life-car" href="/car-affordability-calculator/"><div><b>Car Affordability</b><span>Balance payment and ownership costs</span></div></a><a className="life-card life-home" href="/mortgage-affordability-calculator/"><div><b>Home Affordability</b><span>Estimate your buying power</span></div></a></section>
 <section id="calculator" className="calc"><div className="panel"><div className="eyebrow">YOUR BUDGET</div><h2>Can I afford my life?</h2><label>Country</label><div className="seg"><button onClick={()=>swap('CA')} className={country==='CA'?'on':''}>🇨🇦 Canada</button><button onClick={()=>swap('US')} className={country==='US'?'on':''}>🇺🇸 USA</button></div><label>{country==='CA'?'Province / territory':'State'}</label><select value={region} onChange={e=>setRegion(e.target.value)}>{Object.entries(country==='CA'?CA_PROVINCES:US_STATES).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select><label>Annual gross salary</label><div className="input"><span>$</span><input type="number" value={salary} onChange={e=>setSalary(+e.target.value)}/></div><label>Monthly debt payments</label><div className="input"><span>$</span><input type="number" value={debt} onChange={e=>setDebt(+e.target.value)}/></div><div className="twocol"><div><label>Your rent</label><div className="input"><span>$</span><input value={rent} type="number" onChange={e=>setRent(+e.target.value)}/></div></div><div><label>Car payment</label><div className="input"><span>$</span><input value={car} type="number" onChange={e=>setCar(+e.target.value)}/></div></div></div><small>2026 tax-based planning estimate; actual taxes and personal deductions can differ.</small></div>
 <div className="results"><div className="eyebrow">MONTHLY SNAPSHOT</div><h2>Your affordability snapshot</h2><div className="big"><span>Estimated 2026 take-home</span><strong>{money(r.net,currency)}</strong><small>/ month</small></div><div className="cards"><Result icon="🏠" title="Comfortable rent" val={money(r.comfortable,currency)} note={`Max estimate ${money(r.max,currency)}`}/><Result icon="🚗" title="Suggested car budget" val={money(r.carBudget,currency)} note="payment target"/><Result icon="💰" title="Savings target" val={money(r.save,currency)} note="15% of take-home"/><Result icon={r.left>=0?'✨':'⚠️'} title="Money remaining" val={money(r.left,currency)} note={r.left>=0?'after entered costs':'budget is over target'}/></div><a className="citycta" href="/compare-cities/">Compare this salary across cities →</a></div></section>
 <section className="tools" id="rent"><div className="eyebrow">FREE CALCULATORS</div><h2>One salary. Every decision.</h2><p>Use focused tools when you need a deeper answer.</p><div className="grid"><Tool i="🏠" t="Rent Affordability" d="Estimate comfortable and maximum rent from income and debt." href="/rent-affordability-calculator/"/><Tool i="↩️" t="Income Needed for Rent" d="Start with the rent you want and calculate required income." href="/income-needed-for-rent/"/><Tool i="💵" t="Hourly ↔ Salary" d="Convert hourly, weekly, monthly and annual pay." href="/hourly-to-salary-calculator/"/><Tool i="🧾" t="Take-Home Pay" d="Estimate 2026 net pay for Canada and the United States." href="/take-home-pay-calculator/"/><Tool i="🚙" t="Car Affordability" d="Balance payment, salary, debt and ownership costs." href="/car-affordability-calculator/"/><Tool i="🌆" t="Compare Cities" d="Compare tax-adjusted salary and current rent data by city." href="/compare-cities/"/><Tool i="🎯" t="Salary Needed" d="Work backward from your desired monthly lifestyle to a gross salary target." href="/salary-needed-calculator/"/><Tool i="🏡" t="Home Affordability" d="Estimate a home price and mortgage range from income, debt and down payment." href="/mortgage-affordability-calculator/"/><Tool i="💰" t="Down Payment + Closing Costs" d="Estimate upfront cash needed and a savings timeline for your home target." href="/down-payment-calculator/"/><Tool i="🧭" t="My Financial Plan" d="Connect salary, monthly costs, savings and a home goal, then save the plan on this device." href="/my-plan/"/><Tool i="🎯" t="Goal Planner" d="Build a timeline for a home, emergency fund, debt payoff or custom savings target." href="/goal-planner/"/></div></section>
 <section className="seo"><h2>Built for the questions people actually ask.</h2><div><span>Salary needed to live in Toronto</span><span>Toronto vs Calgary</span><span>NYC vs Miami</span><span>Salary after tax Ontario</span><span>Car affordability by salary</span><span>2026 take-home pay</span></div></section></main><footer className="launchfooter"><div><b>AffordBase.</b><span>Practical affordability estimates for everyday decisions.</span></div><div className="footerlinks"><a href="/about/">About</a><a href="/contact/">Contact</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/disclaimer/">Disclaimer</a></div><small>© 2026 AffordBase</small></footer></>}
function Result({icon,title,val,note}){return <div className="result"><i>{icon}</i><span>{title}</span><strong>{val}</strong><small>{note}</small></div>}
function Tool({i,t,d,href}){return <article><i>{i}</i><h3>{t}</h3><p>{d}</p><a href={href}>Open calculator →</a></article>}
