import Link from 'next/link';
import {notFound} from 'next/navigation';
import Calculator from '../components/Calculator';
import TaxCalculator from '../components/TaxCalculator';
import {pages,getPage} from '../data';
import {SITE_URL} from '../site';

export function generateStaticParams(){return pages.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}){const {slug}=await params,p=getPage(slug);if(!p)return{};const title=p.title,url=`${SITE_URL}/${p.slug}/`;return{title,description:p.description,alternates:{canonical:`/${p.slug}/`},openGraph:{title,description:p.description,url,type:'website',siteName:'AffordBase'}}}

const crossLinks={
 rent:[['/take-home-pay-calculator/','Estimate Take-Home Pay'],['/salary-needed-calculator/','Salary Needed Calculator'],['/mortgage-affordability-calculator/','Mortgage Affordability'],['/dashboard/','Monthly Budget Dashboard']],
 reverse:[['/rent-affordability-calculator/','Rent Affordability Calculator'],['/take-home-pay-calculator/','Take-Home Pay Calculator'],['/salary-needed-calculator/','Salary Needed Calculator'],['/dashboard/','Monthly Budget Dashboard']],
 salary:[['/take-home-pay-calculator/','Take-Home Pay Calculator'],['/rent-affordability-calculator/','Rent Affordability'],['/car-affordability-calculator/','Car Affordability'],['/dashboard/','Monthly Budget Dashboard']],
 tax:[['/rent-affordability-calculator/','Rent Affordability'],['/car-affordability-calculator/','Car Affordability'],['/mortgage-affordability-calculator/','Mortgage Affordability'],['/goal-planner/','Goal Planner']],
 car:[['/take-home-pay-calculator/','Take-Home Pay Calculator'],['/rent-affordability-calculator/','Rent Affordability'],['/dashboard/','Monthly Budget Dashboard'],['/goal-planner/','Goal Planner']],
 mortgage:[['/down-payment-calculator/','Down Payment Calculator'],['/take-home-pay-calculator/','Take-Home Pay Calculator'],['/rent-affordability-calculator/','Rent Affordability'],['/goal-planner/','Goal Planner']],
 city:[['/compare-cities/','Compare Cities'],['/take-home-pay-calculator/','Take-Home Pay Calculator'],['/rent-affordability-calculator/','Rent Affordability'],['/salary-needed-calculator/','Salary Needed Calculator']]
};

function intentContent(p){
 const s=p.slug;
 if(s==='3x-rent-calculator')return {heading:'Understanding the 3x rent guideline',body:'The 3x rent guideline compares monthly gross income with monthly rent. For example, $2,000 rent corresponds to $6,000 in gross monthly income, or $72,000 per year. A landlord may use different qualification rules, so treat this as a reference rather than an approval standard.',faqs:[['Is 3x rent based on gross or take-home income?','The common guideline uses gross income before taxes. Your personal budget should also consider take-home pay, debt, utilities, transportation and savings.'],['What if I do not earn three times the rent?','Qualification policies vary. A lower rent, additional documented income, a roommate or other options may change the situation depending on the landlord and local rules.']]};
 if(s==='40x-rent-calculator')return {heading:'How the 40x rent rule works',body:'The 40x guideline starts with monthly rent and multiplies it by 40 to estimate an annual gross-income target. A $2,500 monthly rent, for example, corresponds to $100,000 in annual gross income. It is a screening reference, not a guarantee that a lease will be approved.',faqs:[['Is the 40x rule the same as the 3x rule?','They are similar but not identical. Three times monthly rent equals 36 times rent annually, while the 40x rule sets a somewhat higher annual-income reference.'],['Does every landlord use 40x rent?','No. Rental qualification standards vary by landlord, property and location.']]};
 const targetRent=s.match(/salary-needed-for-(1500|2000|2500|3000|3500)-rent/);
 if(targetRent){const rent=Number(targetRent[1]),annual=rent*12,three=rent*3*12,forty=rent*40;return {heading:`What income supports ${rent.toLocaleString()} monthly rent?`,body:`At ${rent.toLocaleString()} per month, annual rent is ${annual.toLocaleString()} before utilities and other housing costs. A 3x monthly-income reference corresponds to about ${three.toLocaleString()} in annual gross income, while a 40x annual guideline corresponds to ${forty.toLocaleString()}. Your personal affordability can differ after taxes, debt, transportation and savings.`,faqs:[[`Is ${rent.toLocaleString()} rent affordable for me?`,'Compare the rent with your take-home pay and recurring expenses rather than relying on a qualification ratio alone.'],['Do landlord income rules equal personal affordability?','No. A landlord screening rule focuses on qualification, while personal affordability also considers debt, savings and the rest of your monthly cash flow.']]};}
 if(false)return {heading:'What income supports $2,000 monthly rent?',body:'At $2,000 per month, annual rent is $24,000. A 3x monthly-income reference points to about $6,000 gross income per month, while a 40x annual guideline points to about $80,000 per year. Your comfortable budget may be different after taxes, debt and other expenses.',faqs:[['Is $2,000 rent affordable on a $60,000 salary?','That depends on taxes and the rest of your budget. The calculator lets you compare the rent with income rather than treating a qualification guideline as a personal spending target.'],['Should utilities be included with the $2,000 rent?','For personal budgeting, include utilities and other recurring housing costs even when they are not part of the advertised rent.']]};
 if(false)return {heading:'What income supports $2,500 monthly rent?',body:'A $2,500 monthly rent equals $30,000 per year before utilities and other housing costs. The 40x guideline corresponds to $100,000 in annual gross income, while a 3x monthly-income reference corresponds to $7,500 per month, or $90,000 per year.',faqs:[['Is $100,000 salary enough for $2,500 rent?','Under a simple 40x rent reference it matches the guideline, but personal affordability still depends on taxes, debt, transportation, savings and other expenses.'],['Why does my affordable rent differ from a landlord rule?','A landlord screening rule focuses on qualification. A personal affordability calculation considers the rest of your monthly cash flow.']]};
 const rentSalary=s.match(/how-much-rent-can-i-afford-(60000|80000|100000)-salary/);
 if(rentSalary){const salary=Number(rentSalary[1]),monthly=salary/12,thirty=monthly*.30;return {heading:`Planning rent on a $${salary.toLocaleString()} salary`,body:`A $${salary.toLocaleString()} gross annual salary equals about $${Math.round(monthly).toLocaleString()} per month before taxes. A simple 30% gross-income reference is about $${Math.round(thirty).toLocaleString()} per month for rent. That is only a starting point: taxes, debt, transportation, insurance and savings can make a lower housing target more comfortable.`,faqs:[['Should I use gross or take-home pay for rent planning?','Gross-income ratios are useful for quick comparisons, but take-home pay gives a clearer view of the cash actually available for monthly expenses.'],['Can I afford more if I have no debt?','Lower debt can leave more room in the monthly budget, but savings goals and other recurring expenses should still be included.']]};}
 const hourly=s.match(/(20|25|30|35|40|50)-an-hour-is-how-much-a-year/);
 if(hourly){const rate=Number(hourly[1]),annual=rate*40*52;return {heading:`What $${rate} an hour looks like over a year`,body:`At 40 hours per week for 52 weeks, $${rate} an hour equals $${annual.toLocaleString()} in gross annual pay before taxes. Actual yearly earnings change with weekly hours, unpaid time off, overtime and the number of weeks worked.`,faqs:[['Does this annual figure include taxes?','No. Hourly-to-salary conversion shows gross earnings. Use the take-home pay calculator to estimate modeled taxes and payroll deductions.'],['What if I work fewer than 40 hours a week?','Change the weekly-hours input. The annual estimate should fall proportionally when the hourly rate and weeks worked stay the same.']]};}
 const carSalary=s.match(/car-affordability-(60000|80000)-salary/);
 if(carSalary){const salary=Number(carSalary[1]);return {heading:`Planning a car budget on a $${salary.toLocaleString()} salary`,body:'A vehicle budget should include more than the loan payment. Insurance, fuel, maintenance, registration and other ownership costs compete with rent, debt payments and savings. Use the calculator to test a payment that still leaves room for those recurring costs.',faqs:[['Should I budget from gross salary or take-home pay?','Take-home pay is more useful for monthly cash-flow planning because it reflects the money available after modeled taxes and payroll deductions.'],['Why include ownership costs separately?','A lower loan payment can still lead to an expensive vehicle budget when insurance, fuel and maintenance are high.']]};}
 const fixedTax=s.match(/(60000|70000|100000)-salary-after-tax/);
 if(fixedTax){const salary=Number(fixedTax[1]),monthly=salary/12;return {heading:`Planning with a ${salary.toLocaleString()} gross salary`,body:`A ${salary.toLocaleString()} annual salary equals about ${Math.round(monthly).toLocaleString()} per month before taxes and payroll deductions. Use the calculator to model take-home pay for your location, then connect the monthly net estimate to rent, transportation, savings and home goals.`,faqs:[['Is this the exact tax on this salary?','No. The result is a planning estimate. Filing details, credits, deductions, benefits, local taxes and payroll arrangements can change actual take-home pay.'],['Why does the same salary produce different net pay by location?','Federal, provincial or state taxes and payroll rules vary by jurisdiction, so location can change the modeled result.']]};}
 const houseSalary=s.match(/house-affordability-(60000|80000|100000)-salary/);
 if(houseSalary){const salary=Number(houseSalary[1]);return {heading:`Planning home affordability on a ${salary.toLocaleString()} salary`,body:`A ${salary.toLocaleString()} salary is only one part of home affordability. Down payment, existing debt, mortgage rate, property tax, insurance and HOA or condo fees can materially change the home-price range. Test those inputs together instead of relying on a salary multiple alone.`,faqs:[['Does this result equal a mortgage pre-approval?','No. It is a planning estimate. Lenders can apply different debt, credit, income verification, stress-test, insurance and underwriting rules.'],['Does a larger down payment increase the estimated home price?','It can increase the modeled purchase-price range, but cash reserves, closing costs and lender rules should also be considered.']]};}
 const mortgageTarget=s.match(/income-needed-for-(300|400|500)k-mortgage/);
 if(mortgageTarget){const loan=Number(mortgageTarget[1])*1000;return {heading:`Planning income for a ${loan.toLocaleString()} mortgage`,body:`The income needed for a ${loan.toLocaleString()} mortgage cannot be determined from loan size alone. Interest rate, term, property tax, insurance, HOA or condo fees and existing debt all affect the monthly obligation. Use the calculator to test scenarios rather than treating one salary figure as a lender requirement.`,faqs:[['Is there one required salary for this mortgage amount?','No. Qualification varies with interest rates, debt, credit, property costs, loan rules and lender underwriting.'],['Should I include property tax and insurance?','Yes. They are recurring housing costs and can materially change the income needed to support the total monthly payment.']]};}
 if(s==='house-affordability-by-salary')return {heading:'Connect salary to the full cost of owning a home',body:'Salary multiples are a quick reference, but a home budget is stronger when it includes take-home pay, existing debt, down payment, mortgage rate, property tax, insurance and HOA or condo fees. Adjust the calculator inputs to see how each assumption changes the estimated range.',faqs:[['Should I use gross salary or take-home pay?','Lenders often evaluate gross income under their own rules, while take-home pay is useful for understanding your personal monthly cash flow.'],['Is the estimated home price guaranteed?','No. It is an educational planning estimate and not a mortgage approval or lending offer.']]};
 if(p.type==='tax')return {heading:'Use take-home pay for monthly planning',body:'Gross salary is useful for comparing jobs, but monthly decisions are usually paid from net income. Use this estimate to connect salary with rent, car costs, savings and housing goals. Tax results are modeled estimates and can differ with filing details, credits, deductions and individual circumstances.',faqs:[['Is this an official tax calculation?','No. It is a planning estimate and should not replace a tax return, payroll statement or current government guidance.'],['Why can actual take-home pay be different?','Benefits, withholding choices, credits, deductions, local taxes and payroll arrangements can change actual net pay.']]};
 if(p.type==='car')return {heading:'Look beyond the monthly car payment',body:'Car affordability depends on financing and the recurring cost of ownership. Compare the payment with insurance, fuel, maintenance and the rest of your monthly budget before deciding what price range feels sustainable.',faqs:[['Does a longer loan make a car more affordable?','It can reduce the monthly payment but may increase total interest and keep the loan outstanding longer.'],['Should a down payment come from emergency savings?','That is a personal financial decision. The calculator is designed to compare scenarios rather than recommend using money reserved for emergencies.']]};
 return {heading:'Use the estimate as a planning starting point',body:'Adjust the calculator inputs to reflect your own income, debt and monthly costs. Comparing more than one scenario can show which assumptions have the largest effect on your budget.',faqs:[['Is this result guaranteed?','No. AffordBase provides planning estimates, not lender, landlord, tax or financial approvals.'],['What should I compare next?','Use the related calculators below to connect this estimate with take-home pay, housing, transportation and savings.']]};
}

export default async function Page({params}){
 const {slug}=await params,p=getPage(slug);if(!p)notFound();const type=p.type==='city'?'rent':p.type;
 const region=slug.includes('ontario')?'ON':slug.includes('quebec')?'QC':slug.includes('california')?'CA':slug.includes('texas')?'TX':undefined;const country=slug.includes('california')||slug.includes('texas')?'US':'CA';const url=`${SITE_URL}/${p.slug}/`;const intent=intentContent(p);
 const schema={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:p.title,url,description:p.description,applicationCategory:"FinanceApplication",operatingSystem:"Web",offers:{"@type":"Offer",price:"0",priceCurrency:country==='US'?'USD':'CAD'}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"AffordBase",item:SITE_URL},{"@type":"ListItem",position:2,name:p.title,item:url}]},{"@type":"FAQPage",mainEntity:intent.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
 const links=crossLinks[p.type]||crossLinks[type]||[];
 return <main className="landing"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="crumb"><Link href="/">Home</Link> / {p.title}</div><section className="pagehero"><div className="eyebrow">FREE AFFORDABILITY TOOL</div><h1>{p.h1}</h1><p>{p.description} Change the numbers below to see the estimate instantly.</p></section>{p.type==='tax'?<TaxCalculator initialCountry={country} initialRegion={region}/>:<Calculator type={type}/>}<section className="content"><h2>{intent.heading}</h2><p>{intent.body}</p><h2>Frequently asked questions</h2>{intent.faqs.map(([q,a])=><div className="faqItem" key={q}><h3>{q}</h3><p>{a}</p></div>)}<h2>Continue your affordability plan</h2><div className="linkgrid">{links.map(([href,label])=><Link key={href} href={href}>{label} →</Link>)}</div><h2>Explore related calculators</h2><div className="linkgrid">{pages.filter(x=>x.type===p.type&&x.slug!==p.slug).slice(0,6).map(x=><Link key={x.slug} href={`/${x.slug}/`}>{x.title} →</Link>)}</div></section></main>;
}