import Link from 'next/link';
export const metadata={title:'Financial Guides & Articles',description:'Practical AffordBase guides about salary, rent, mortgages, home buying and cost of living in Canada and the United States.',alternates:{canonical:'/articles/'}};
const articles=[
 {href:'/articles/how-much-should-you-spend-on-rent-30-rule/',tag:'RENT BUDGET',title:'How Much Should You Spend on Rent? 30% Rule vs Real Budget',desc:'Understand Canada’s 30% benchmark, then build a realistic rent target around take-home pay, debt, savings and real expenses.',cls:'article-card-rent-30-rule'},
 {href:'/articles/how-much-house-can-i-afford-100k-salary-canada/',tag:'HOME AFFORDABILITY',title:'How Much House Can I Afford on a $100K Salary in Canada?',desc:'See how mortgage rules, the stress test, down payment and debt shape a $100K household’s 2026 home budget.',cls:'article-card-100k-house'},
 {href:'/articles/is-renting-getting-cheaper-canada-2026/',tag:'CANADA RENT TRENDS',title:'Is Renting Getting Cheaper in Canada in 2026?',desc:'See where asking rents are falling or rising and what Canada’s easing rental market really means for your budget.',cls:'article-card-canada-rent-trends'},
 {href:'/articles/vancouver-vs-toronto-cost-of-living/',tag:'CITY COMPARISON',title:'Vancouver vs Toronto Cost of Living: Salary, Rent & Housing',desc:'Compare 2026 rent, housing, salary needs, taxes and monthly-budget trade-offs using current Canadian data.',cls:'article-card-vancouver-toronto'},
 {href:'/articles/toronto-vs-calgary-cost-of-living-2026/',tag:'CITY COMPARISON',title:'Toronto vs Calgary Cost of Living 2026',desc:'Compare rent, housing, taxes, transportation and the monthly budget using current 2026 data.',cls:'article-card-toronto-calgary'},
 {href:'/articles/how-much-rent-can-i-afford-toronto-2026/',tag:'TORONTO RENT',title:'How Much Rent Can I Afford in Toronto in 2026?',desc:'Use current Toronto rent data, income benchmarks and a realistic monthly budget to find your rent target.',cls:'article-card-toronto'},
 {href:'/articles/income-needed-to-buy-house-canada-2026/',tag:'HOME BUYING',title:'How Much Income Do You Need to Buy a House in Canada in 2026?',desc:'Understand mortgage qualification, GDS/TDS ratios, the stress test, down payments and closing costs.',cls:'article-card-home'},
 {href:'/articles/rent-vs-buy-canada-2026/',tag:'HOUSING',title:'Rent vs Buy in Canada 2026: Which Costs Less?',desc:'Compare current rents, ownership costs, mortgage considerations, flexibility and long-term equity.',cls:'article-card-rent'}
];
export default function Articles(){return <main className="articles-index"><section className="articles-index-hero"><span>GUIDES & INSIGHTS</span><h1>Make smarter money decisions.</h1><p>Clear, practical guides built around the financial questions people actually ask—salary, rent, cities, cars and buying a home.</p></section><section className="articles-grid">{articles.map(a=><Link href={a.href} className={'article-index-card '+a.cls} key={a.href}><div className="article-card-image"></div><div className="article-card-copy"><small>{a.tag} · 2026</small><h2>{a.title}</h2><p>{a.desc}</p><strong>Read the guide →</strong></div></Link>)}</section><section className="articles-tools"><div><span>FREE AFFORDBASE TOOLS</span><h2>Turn what you learn into a plan.</h2></div><div><Link href="/take-home-pay-calculator/">Salary</Link><Link href="/rent-affordability-calculator/">Rent</Link><Link href="/mortgage-affordability-calculator/">Mortgage</Link><Link href="/compare-cities/">Compare Cities</Link></div></section></main>}