import Link from 'next/link';
import MortgageStressTestCanada from '../components/MortgageStressTestCanada';
import {SITE_URL} from '../site';

export const metadata={title:'Mortgage Stress Test Calculator Canada 2026',description:'Estimate Canada mortgage stress-test qualification using the higher of 5.25% or your contract rate plus 2%, with GDS and TDS reference ratios.',alternates:{canonical:'/mortgage-stress-test-calculator-canada/'},openGraph:{title:'Mortgage Stress Test Calculator Canada 2026',description:'Estimate the qualifying mortgage rate, GDS and TDS for Canadian mortgage planning.',url:`${SITE_URL}/mortgage-stress-test-calculator-canada/`,type:'website',siteName:'AffordBase'}};

export default function Page(){
 const url=`${SITE_URL}/mortgage-stress-test-calculator-canada/`;
 const faq=[['What is the mortgage stress-test rate in Canada?','For federally regulated lenders, the qualifying rate is generally the higher of 5.25% or the mortgage contract rate plus 2 percentage points.'],['What are GDS and TDS?','GDS compares qualifying housing costs with gross household income, while TDS also includes other debt obligations. Federal consumer guidance uses 39% GDS and 44% TDS as general reference ceilings.'],['Does passing these ratios guarantee mortgage approval?','No. This calculator is educational. Credit, income verification, property details, mortgage insurance, lender policies and other underwriting requirements can affect approval.']];
 const schema={'@context':'https://schema.org','@graph':[{'@type':'WebApplication',name:'Mortgage Stress Test Calculator Canada',url,applicationCategory:'FinanceApplication',operatingSystem:'Web',offers:{'@type':'Offer',price:'0',priceCurrency:'CAD'}},{'@type':'FAQPage',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]};
 return <main className="landing"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="crumb"><Link href="/">Home</Link> / Mortgage Stress Test Calculator Canada</div><section className="pagehero"><div className="eyebrow">CANADA · 2026</div><h1>Mortgage Stress Test Calculator Canada</h1><p>Estimate your qualifying rate and compare housing costs with the 39% GDS and 44% TDS reference ratios used in Canadian mortgage planning.</p></section><MortgageStressTestCanada/><section className="content"><h2>How the Canadian mortgage stress test works</h2><p>The stress test checks whether the mortgage can be supported at a qualifying rate above the contract rate. For federally regulated lenders, the qualifying rate is generally the higher of 5.25% or the contract rate plus 2 percentage points. The calculator also estimates GDS and TDS so you can see how housing costs and other debt interact with gross household income.</p><h2>Frequently asked questions</h2>{faq.map(([q,a])=><div className="faqItem" key={q}><h3>{q}</h3><p>{a}</p></div>)}<h2>Continue your mortgage plan</h2><div className="linkgrid"><Link href="/mortgage-payment-calculator-canada/">Mortgage Payment Calculator →</Link><Link href="/mortgage-affordability-calculator/">Canada Mortgage Affordability →</Link><Link href="/mortgage-affordability-calculator-ontario/">Ontario Mortgage Calculator →</Link><Link href="/mortgage-affordability-calculator-alberta/">Alberta Mortgage Calculator →</Link><Link href="/mortgage-affordability-calculator-quebec/">Quebec Mortgage Calculator →</Link><Link href="/income-needed-for-600k-mortgage/">Income Needed for $600K Mortgage →</Link></div></section></main>
}