import Link from 'next/link';
import MortgagePaymentCanada from '../components/MortgagePaymentCanada';
import {SITE_URL} from '../site';

export const metadata={title:'Mortgage Calculator Canada 2026 | Monthly Payment Calculator',description:'Use our free mortgage calculator Canada 2026 to estimate monthly mortgage payments from home price, down payment, interest rate and amortization.',alternates:{canonical:'/mortgage-payment-calculator-canada/'},openGraph:{title:'Mortgage Calculator Canada 2026 | Monthly Payment Calculator',description:'Estimate your monthly mortgage payment in Canada from home price, down payment, mortgage rate and amortization.',url:`${SITE_URL}/mortgage-payment-calculator-canada/`,type:'website',siteName:'AffordBase'}};

export default function Page(){
 const url=`${SITE_URL}/mortgage-payment-calculator-canada/`;
 const faq=[['How is a mortgage payment calculated in Canada?','The payment depends on the mortgage principal, interest rate, amortization and payment frequency. This calculator provides a monthly planning estimate.'],['Does the payment include property tax and heating?','The main mortgage payment is principal and interest. The calculator also lets you add property tax, heating and condo fees to see a broader housing-cost estimate.'],['Is the mortgage payment the same as the stress-test payment?','No. Mortgage qualification may use a higher qualifying rate. Use the Canada Mortgage Stress Test Calculator to compare the qualifying rate and debt-service ratios.']];
 const schema={'@context':'https://schema.org','@graph':[{'@type':'WebApplication',name:'Mortgage Payment Calculator Canada',url,applicationCategory:'FinanceApplication',operatingSystem:'Web',offers:{'@type':'Offer',price:'0',priceCurrency:'CAD'}},{'@type':'FAQPage',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]};
 return <main className="landing"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="crumb"><Link href="/">Home</Link> / Mortgage Payment Calculator Canada</div><section className="pagehero"><div className="eyebrow">CANADA · 2026</div><h1>Mortgage Calculator Canada 2026</h1><p>Estimate your monthly mortgage payment in Canada from home price, down payment, mortgage interest rate and amortization, then add property tax, heating and condo fees to see a broader monthly housing cost.</p></section><section className="content quickanswer"><strong>Quick answer:</strong> Enter your home price, down payment, mortgage rate and amortization below to estimate the <b>monthly mortgage payment</b>. Then add recurring housing costs for a more complete monthly estimate.</section><MortgagePaymentCanada/><section className="content"><h2>Mortgage calculator Canada: estimate your monthly payment</h2><p>Your mortgage payment is driven mainly by the amount borrowed, the mortgage interest rate and the amortization period. A larger down payment reduces the mortgage principal, while a higher rate generally increases the payment required for the same balance.</p><h2>Plan the payment before you plan the purchase price</h2><p>A mortgage payment is only one part of homeownership. Compare the principal-and-interest payment with property tax, heating, condo fees, insurance, maintenance and your other monthly obligations.</p><h2>Frequently asked questions</h2>{faq.map(([q,a])=><div className="faqItem" key={q}><h3>{q}</h3><p>{a}</p></div>)}<h2>Continue your mortgage plan</h2><div className="linkgrid"><Link href="/mortgage-stress-test-calculator-canada/">Mortgage Stress Test Calculator →</Link><Link href="/mortgage-affordability-calculator/">Canada Mortgage Affordability →</Link><Link href="/down-payment-calculator/">Down Payment Calculator →</Link><Link href="/closing-cost-calculator/">Closing Cost Calculator →</Link><Link href="/house-affordability-100000-salary/">House Affordability on $100K →</Link><Link href="/income-needed-for-500k-mortgage/">Income Needed for $500K Mortgage →</Link></div></section></main>
}